services:
    ai_gallery.upload_listener:
        class: Ai\GalleryBundle\EventListener\ImageUploaderListener
        arguments:    ['@doctrine.orm.default_entity_manager', '@liip_imagine.cache.manager', '@liip_imagine.data.manager', '@liip_imagine.filter.manager', '%kernel.root_dir%']
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

    ai_gallery.album_listener:
        class: Ai\GalleryBundle\EventListener\AlbumListener
        arguments: ['@ai_gallery.image_manager']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove}

    ai_gallery.image_listener:
        class: Ai\GalleryBundle\EventListener\ImageListener
        arguments: ['@ai_gallery.image_manager']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove}

    ai_gallery.image_manager:
        class: Ai\GalleryBundle\Services\ImageManager
        arguments:
            - '@liip_imagine.cache.manager'
            - '@liip_imagine.data.manager'
            - '@liip_imagine.filter.manager'
            - '@oneup_uploader.orphanage_manager'
            - '@filesystem'
            - '%kernel.root_dir%'

    ai_gallery.form.type.image:
            class: Ai\GalleryBundle\Form\Type\ImageType
            arguments:
                - '@doctrine.orm.default_entity_manager'
            tags:
                - { name: form.type }

    ai_gallery.form.type.album:
            class: Ai\GalleryBundle\Form\Type\AlbumType
            arguments:
                - '@doctrine.orm.default_entity_manager'
                - '@ai_gallery.form.type.image'
            tags:
                - { name: form.type }