<?php

namespace Ai\GalleryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    /**
     * Gets search result
     *
     * @param string|null $search
     * @param integer|null $maxResults
     * @return array
     */
    public function findBySearch($search = null, $maxResults = null)
    {
        return $this->findBySearchQuery($search, $maxResults)->getResult();
    }

    /**
     * Gets search query
     *
     * @param string|null $search
     * @param integer|null $maxResults
     * @return \Doctrine\ORM\Query
     */
    public function findBySearchQuery($search = null, $maxResults = null)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->select('a.id, a.name, a.descr, a.icon')
            ->orderBy('a.tstamp', 'DESC');

        if (null != $search) {
            $qb->where(
                $qb->expr()->orX(
                    $qb->expr()->like('a.name', ':search'),
                    $qb->expr()->like('a.descr', ':search')
                )
            );
            $qb->setParameter('search', $search . '%');
        }

        if (null !== $maxResults) {
            $qb->setMaxResults($maxResults);
        }

        return $qb->getQuery();
    }
}
