<?php

namespace Ai\GalleryBundle\Repository;

use Ai\GalleryBundle\Entity\Album;
use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    /**
     * Gets search result
     *
     * @param string|null $search
     * @param integer|null $maxResults
     * @return array
     */
    public function findBySearch($search = null, $maxResults = null)
    {
        return $this->findBySearchQuery($search, $maxResults)->getResult();
    }

    /**
     * Gets search query
     *
     * @param string|null $search
     * @param integer|null $maxResults
     * @return \Doctrine\ORM\Query
     */
    public function findBySearchQuery(Album $album, $search = null, $maxResults = null)
    {
        $qb = $this->createQueryBuilder('i');

        $qb
            ->select('i.id, i.name, i.image')
            ->where('i.album=:album')
            ->orderBy('i.tstamp', 'DESC')
            ->setParameter('album', $album)
        ;

        if (null != $search) {
            $qb->andWhere(
                $qb->expr()->like('i.name', ':search')
            );
            $qb->setParameter('search', $search . '%');
        }

        if (null !== $maxResults) {
            $qb->setMaxResults($maxResults);
        }

        return $qb->getQuery();
    }
}
